### ISSUE TITLE
Dictionaries are not available when installed locally

### ISSUE THREAD

**Issue by arteymix** [Kozea/Pyphen#10]
If you install Pyphton with the `--user` option with `pip`, no language is available.

**Comment by menegon** [comment]
I provide additional details on Ubuntu 14.04 

- pip install pyphen (as root)
- the dictionaries are istalled in /usr/local/share/pyphen
- however pyphen.dictionaries_roots returns
   (u'/usr/local/lib/python2.7/dist-packages/share/pyphen/dictionaries',
    u'/usr/share/pyphen/dictionaries',
    u'/usr/local/lib/python2.7/dist-packages/dictionaries')

**Comment by jdevera** [comment]
For the same reason, it does not work within a virtual environment.

**Comment by liZe** [comment]
Does it work better with the wheel package?

**Comment by bjodah** [comment]
I can confirm this on Ubuntu 14.04. wheel package makes no difference.

**Comment by liZe** [comment]
See https://bitbucket.org/pypa/setuptools/issues/130/install_data-doesnt-respect-prefix

**Comment by liZe** [comment]
I've tried different use cases (Gentoo, Python 3.4), and here's what I get:
- `pip install` works as root
- `pip install` works in a virtualenv
- `pip install --user` doesn't work

I'll try to find a solution that at least fixes the problem for me with `--user`, and see if it fixes the problem for you for other cases.

**Comment by liZe** [comment]
As `data_files` is broken in so many ways, using `package_data` seems to be the only reliable solution left.
