### ISSUE TITLE
Support for LibreOffice Language Extension for Chinese, etc

### ISSUE THREAD

**Issue by loretoparisi** [Kozea/Pyphen#12]
Is it possibile to add support for LibreOffice extensions for languages not here

http://cgit.freedesktop.org/libreoffice/dictionaries/plain/

like Chinese, etc.
The extension should be this in the LanguageTools here

http://extensions.libreoffice.org/extension-center/languagetool

but I'm not sure if the dictionaries are in the same format of the pre installed ones.

**Comment by liZe** [comment]
Unfortunately, this extension doesn't use the same format for hyphenation dictionaries (it actually looks like code more than dictionaries), so we won't be able to include them in Pyphen.
