### ISSUE TITLE
Split method?

### ISSUE THREAD

**Issue by tmp6154** [Kozea/Pyphen#16]
I was surprised there's no method to split input text into list of tokens. I ended up writing following function:

```
def splitWord(word, splits) :
        if len(splits) == 0:
          return [word]
        else:
          firstidx = 0
          lastidx = 0
          syls = []
          while splits:
            firstidx = lastidx
            lastidx = splits.pop(0)
            syls.append(word[firstidx:lastidx])
          syls.append(word[lastidx:])
          return syls
```

With minor adjustments, it could be added to library (get splitpoints with Pyphen.positions for input, then perform split on them).

**Comment by vmesel** [comment]
You can use the string that is returned on the function and make a:

```
splitted_word = stringOutput.split("-")
```

**Comment by liZe** [comment]
> You can use the string that is returned

Yes, `Pyphen.inserted(word).split('-')` is what you want!

**Comment by tmp6154** [comment]
But what if hyphenated string already contained hyphens? It would be off. Moreover, if there's consecutive hyphens, then there would be empty strings in resulting list, which is unwanted.

**Comment by liZe** [comment]
Another solution:

```python
indexes = dic.positions(word)
[word[i:j] for i, j in zip([0] + indexes, indexes + [None])]
```

**Comment by tmp6154** [comment]
Well, I like this solution, much more compact compared to my original function.
