### ISSUE TITLE
'uni' considered one syllable

### ISSUE THREAD

**Issue by adammichaelwood** [Kozea/Pyphen#20]
```
>>> dic = pyphen.Pyphen(lang='en_US')
>>> dic.inserted("universal")
'uni-ver-sal'
>>> dic.inserted("university")
'uni-ver-si-ty'
>>> dic.inserted("universe")
'uni-verse'
>>> dic.inserted("uni")
'uni'
```

**Comment by liZe** [comment]
Hello @adammichaelwood, thank you for taking the time to report this issue.

There are two parameters called `left` and `right` in `Pyphen.__init__`, fixing the minimum of characters in the first and last syllabes. As their default values are `2`, you get this behaviour. You can use `1` to fix your problem.

```python
>>> dic = pyphen.Pyphen(lang='en_US', left=1, right=1)
>>> dic.inserted("universal")
'u-ni-ver-sal'
```

I've added a paragraph in the documentation about using `help(pyphen)` to get the whole documentation of the API.

**Comment by adammichaelwood** [comment]
Thanks for the tip!

**Comment by aletote** [comment]
When I do that I still get 'even' instead of 'e-ven' and now I get also 'y-our' instead of 'your'.
