### ISSUE TITLE
Exception when word not found in dict?

### ISSUE THREAD

**Issue by MoyanZitto** [Kozea/Pyphen#21]
Hi, is it possible to raise an exception when query word is not in current dictionary?
Now it is very possible for pyphen to return 1 for nonsense input, which is quite confusing.

**Comment by liZe** [comment]
Hello!

We can’t do this, because hyphenation dictionaries don’t always list words. Some languages (French for example) rely on rules that can work on unknown words (that’s really cool), and its dictionary only includes words for exceptions.
