### ISSUE TITLE
There is no Arabic dictionary

### ISSUE THREAD

**Issue by yusufadell** [Kozea/Pyphen#33]
There is no Arabic dic although There are around 280 million Arabic native speakers worldwide, including me!

**Comment by yusufadell** [comment]
I have tried to get one from [LibreOffice Dictionaries](https://github.com/LibreOffice/dictionaries/tree/master/ar)

But i have found that  its size is huge comparing to already existing dictionaries about 7M.

**Comment by liZe** [comment]
Hello @yusufadell.

> There are around 280 million Arabic native speakers worldwide, including me!

You’re right, we’d love to include an Arabic hyphenation dictionary too! Unfortunately, we rely on LibreOffice dictionaries, and there’s no Arabic hyphenation dictionary available for LibreOffice yet. The dictionary you’re talking about is a spelling dictionary, not an hyphenation dictionary, that’s why it’s huge.

A solution to know if there’s a simple way to find or to create an Arabic hyphenation dictionary could be to contact [the people who created the spelling dictionary](https://github.com/LibreOffice/dictionaries/blob/master/ar/AUTHORS.txt). Maybe they can help!
