### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by discover59** [Kozea/Pyphen#35]
I realized that this library is in tri-license and it's used in weazyprint library.

Does it mean I cannot use weazyprint in private repo for commercial application?

Any comment is appreciated.

**Comment by grewn0uille** [comment]
Hello!

If you want to have details about how Pyphen tri-license works, you can have a look at https://github.com/Kozea/WeasyPrint/issues/944.
There is no problem to use WeasyPrint in a private repo for a commercial app.

**Comment by discover59** [comment]
Thank you @grewn0uille.
Glad that I can use it in commercial app.
