### ISSUE TITLE
Conda Forge

### ISSUE THREAD

**Issue by thewchan** [Kozea/Pyphen#41]
Hello! I have successfully put this package on to Conda Forge, and I am extending the invitation for the owner/maintainers of this package to be maintainers on Conda Forge as well. Let me know if you are interested! Thanks.
https://github.com/conda-forge/pyphen-feedstock

**Comment by liZe** [comment]
Thank you! You can add me as a co-maintainer, no problem.

**Comment by thewchan** [comment]
Thanks @liZe I will do so!
