### ISSUE TITLE
pytest-3.8: error: unrecognized arguments: --isort --flake8 --numprocesses=auto

### ISSUE THREAD

**Issue by yarunachalam** [Kozea/Pyphen#42]
pytest fails

+ pytest-3.8 --ignore=_build.python38 --ignore=_build.python39 --ignore=_build.python310 -v
[   32s] ERROR: usage: pytest-3.8 [options] [file_or_dir] [file_or_dir] [...]
[   32s] pytest-3.8: error: unrecognized arguments: --isort --flake8 --numprocesses=auto
[   32s]   inifile: /home/abuild/rpmbuild/BUILD/Pyphen-0.13.0/pyproject.toml

**Comment by liZe** [comment]
Hi.

If you want to launch tests with Pytest, you can install it using `pip install pyphen[test]` that will install required dependencies. If you don’t want to use these dependencies, you can remove [this line](https://github.com/Kozea/Pyphen/blob/72ca44c74188353a2a798d26f53953e159ea70b1/pyproject.toml#L50).

(Note that we’ll probably remove this line soon, [as we did in other libraries](https://github.com/Kozea/WeasyPrint/commit/b9c086d9861e659af79100086ec0bcd5bdfeafba).)
