### ISSUE TITLE
Replace deprecated pkg_resources with importlib_resources

### ISSUE THREAD

**Issue by nidico** [Kozea/Pyphen#48]
`pkg_resources` throws a DeprecationWarning as of setuptools 67.5.0 (see [changelog](https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v6750)), therefore `pkg_resources.resource_filename` should be replaced by [importlib_resources](https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename) (for compatibility with Python < 3.9, otherwise [`importlib.resources`](https://docs.python.org/3/library/importlib.resources.html#importlib.resources.files) could be used).

**Comment by liZe** [comment]
Thanks for the report!

**Comment by st-pasha** [comment]
Would it be possible to make a new release with these changes in place?

**Comment by nidico** [comment]
Pyphen 0.14.0 has been released.
