### ISSUE TITLE
Several issues about the updating script

### ISSUE THREAD

**Issue by BLKSerene** [Kozea/Pyphen#57]
Hi, I've found several issues that could be fixed or improved about the script used to automatically update all hyphenation dictionaries.

1. The hyphen in the file name of the Serbian dictionary `hyph_sr-Latn.dic` would not be replaced by an underscore (the `rename` command does not work).
2. READMEs of dictionaries are added in [this commit](https://github.com/Kozea/Pyphen/commit/5d80cf8ffb9fdff4e2d67fa19dd1b6b76a79c71c) recently, so the script should also update them accordingly.
3. The repo of LibreOffice's dictionaries cloned locally should be removed automatically after updating (otherwise they need to be removed by hand before commiting the change).

**Comment by liZe** [comment]
Hi!

> 1. The hyphen in the file name of the Serbian dictionary `hyph_sr-Latn.dic` would not be replaced by an underscore (the `rename` command does not work).

It does for me. I think that there are different `rename` programs, that’s [the one I have on my computer](https://www.man7.org/linux/man-pages/man1/rename.1.html). Do you have another one?

It’s possible to replace this by a loop and a simple `mv` command.

> 2. READMEs of dictionaries are added in [this commit](https://github.com/Kozea/Pyphen/commit/5d80cf8ffb9fdff4e2d67fa19dd1b6b76a79c71c) recently, so the script should also update them accordingly.

I won’t do this, and I think that it’ll be difficult to automatize. But if anyone wants to open a PR… 😄

> 3. The repo of LibreOffice's dictionaries cloned locally should be removed automatically after updating (otherwise they need to be removed by hand before commiting the change).

It’s already [in `.gitignore`](https://github.com/Kozea/Pyphen/blob/3e48596eb0f81f6fb466fe7a0451fd61df2ad7cd/.gitignore#L7).

**Comment by BLKSerene** [comment]
> It does for me. I think that there are different rename programs, that’s [the one I have on my computer](https://www.man7.org/linux/man-pages/man1/rename.1.html). Do you have another one?

I'm using the bash shell installed with Git on Windows, not sure why `rename` does not work...
But if it works for others, I suppose it's fine.



> It’s already [in .gitignore](https://github.com/Kozea/Pyphen/blob/3e48596eb0f81f6fb466fe7a0451fd61df2ad7cd/.gitignore#L7).

Indeed, there's another problem. The updating script tries to re-cloning the LibreOffice's dictionary repo each time it is run, but if I want to run the script to update the dictionaries again, I need to first remove the old repo cloned locally.

**Comment by liZe** [comment]
> Indeed, there's another problem. The updating script tries to cloning the LibreOffice's dictionary repo each time it is run, but if I want to run the script to update the dictionaries again, I need to first remove the old repo cloned locally.

OK, I understand.

The goal is actually to keep the repository if it exists, there’s no need to clone it again and again. Currently, if the repository exists, the clone command fails, that’s what we want. What we could do is to hide the error.
