### ISSUE TITLE
Support for the Latin language

### ISSUE THREAD

**Issue by bi3mw** [Kozea/Pyphen#59]
Hello,
It would be nice if pyphen also supported the Latin language. Is this possible ?

**Comment by bi3mw** [comment]
Can you also provide a list of supported languages with the corresponding country code (e.g. de_DE for German ) ?

**Comment by liZe** [comment]
Hi!

> It would be nice if pyphen also supported the Latin language. Is this possible ?

Pyphen uses the hyphenation dictionaries included in LibreOffice (see https://cgit.freedesktop.org/libreoffice/dictionaries/tree/), but there’s no Latin dictionary available (yet?).

> Can you also provide a list of supported languages with the corresponding country code (e.g. de_DE for German ) ?

You can check [the (maybe old) list provided by LibreOffice](https://wiki.documentfoundation.org/Development/Dictionaries). Note that not all the langages listed on this page have a dictionary for hyphenation, the list of supported langages is available on [pyphen.org](https://pyphen.org).

**Comment by bi3mw** [comment]
Thanks for the information.
I have seen the list of supported languages. I have added the corresponding country codes as best I could. The codes with question marks are probably incomplete. Can these be completed ?

   language_country_names = {
    'Afrikaans',  af_ZA
    'Albanian', sq ?
    'Belarusian', be ?
    'Bulgarian', bg_BG
    'Catalan', ca ?
    'Croatian', hr_HR
    'Czech', cs_CZ
    'Danish', da_DK
    'Dutch', nl_NL
    'English (Great Britain)', en_GB
    'English (United States)', en_US
    'Esperanto', eo ?
    'Estonian', et_EE
    'French', fr_FR
    'Galician', gl ?
    'German (Austria)', de_AT
    'German (Germany)', de_DE
    'German (Switzerland)', de_CH
    'Greek', el_GR
    'Hungarian', hu_HU
    'Icelandic', is_IS
    'Indonesian', id ?
    'Italian', it_IT
    'Lithuanian', lt_LT
    'Latvian', lv_LV
    'Mongolian', mn ?
    'Norwegian (Bokmål)', nb_NO
    'Norwegian (Nynorsk)', nn_NO
    'Polish', pl_PL
    'Portuguese (Brazil)', pt_BR
    'Portuguese (Portugal)', pt_PT
    'Romanian', ro_RO
    'Russian', ru_RU
    'Serbian (Cyrillic)', sr_Cyrl
    'Serbian (Latin)', sr_Latn
    'Slovak', sk_SK
    'Slovenian', sl_SI
    'Spanish', es_ES
    'Swedish', sv ?
    'Telugu', te_IN
    'Thai', th ?
    'Ukrainian', uk_UA
    'Zulu', zu_ZA
}

**Comment by liZe** [comment]
> The codes with question marks are probably incomplete.

They are not incomplete. The language is only the first part of the code, but it’s possible to add more parts if you want to be more specific, by adding a reference to a country or a writing system for example. The creators of the dictionaries decided to name their dictionaries depending on whether these extra attributes were relevant or not.

You can check [RFC 5646](https://www.rfc-editor.org/rfc/rfc5646.txt) for more information.

**Comment by bi3mw** [comment]
Thank you very much.
