### ISSUE TITLE
ResourceWarning: unclosed file

### ISSUE THREAD

**Issue by gregorias** [Kozea/Pyphen#66]
Since https://github.com/Kozea/Pyphen/commit/1795d65b7307f3b92d03e08d690caec3b47c5229#diff-c99bbcfc0e7112a9ae7a56a9af9b33a1b503dafc3bbdaf6f2a753bd62fd2a6e4R122, Pyphen opens a dictionary without properly closing it at https://github.com/Kozea/Pyphen/blob/099eeb71968446f3d00c743870f0fa05ec1748ad/pyphen/__init__.py#L118.

This results in a resource warning:

```
/Users/grzesiek/Code/anki/anki-word-hyphenator/deps/Pyphen/pyphen/__init__.py:118: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/grzesiek/Code/anki/anki-word-hyphenator/deps/Pyphen/pyphen/dictionaries/hyph_en_US.dic'>
  encoding = path.open('rb').readline().decode()
```

**Comment by liZe** [comment]
Thanks for the report!
