### ISSUE TITLE
Problem with path.open

### ISSUE THREAD

**Issue by rpspringuel** [Kozea/Pyphen#68]
I'm working with the syllabify script from [hyphen-la](https://github.com/gregorio-project/hyphen-la) repository and am running up against what appears to be a problem with Pyphen.  The last lines of the stack trace read as follows:

```
File "/Users/ss/Library/Python/3.12/lib/python/site-packages/pyphen/__init__.py", line 117, in __init__
    with path.open('rb') as fd:
         ^^^^^^^^^
AttributeError: 'str' object has no attribute 'open'
```

This suggests to me that the path variable is being misinterpreted as a str rather than as a path to a file that can be opened.  Doing some search online, I found a [StackOverflow question](https://stackoverflow.com/questions/22121612/reads-pathfile-as-string-attributeerror-str-object-has-no-attribute-open) which talks about this sort of error, but it's flagged for Python 2.7, not Python 3.*.  Still, I took it as a starting point and came up with this [diff.patch](https://github.com/user-attachments/files/18137046/diff.patch).

I'm not submitting this as a PR because it removes the attempted detection of encoding and instead relies on the input being in Unicode (the default assumption for Python).  I couldn't find an encoding detection method that doesn't require importing a new package and I didn't want to add a dependency.

**Comment by liZe** [comment]
Hi!

Thanks for the report. Could you please share the whole stack?

**Comment by rpspringuel** [comment]
The whole stack trace was as follows:

```
syllabify returned error number 1
Traceback (most recent call last):
  File "/Users/ss/Documents/Programming/hyphen-la/syllabifier/syllabify.py", line 157, in <module>
    hyphenator = pyphen.Pyphen(filename=dir_path+'/../patterns/hyph_la_'+args.mode+'.dic',left=lefthyphenmin,right=righthyphenmin)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ss/Library/Python/3.12/lib/python/site-packages/pyphen/__init__.py", line 223, in __init__
    hdcache[filename] = HyphDict(filename)
                        ^^^^^^^^^^^^^^^^^^
  File "/Users/ss/Library/Python/3.12/lib/python/site-packages/pyphen/__init__.py", line 117, in __init__
    with path.open('rb') as fd:
         ^^^^^^^^^
AttributeError: 'str' object has no attribute 'open'
```

**Comment by liZe** [comment]
Should be fixed in `main`, feedback is welcome!

**Comment by rpspringuel** [comment]
Initial testing has it working just fine.  Thanks.
